<a href="https://colab.research.google.com/github/sararotenski/AlgoritmosEProgramacao/blob/main/aula_2005.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Pandas
#Ele facilita a manipulação e a análise de dados tabulares
#Pandas utiliza numpy arrays como estrutura de dados base, o
#que traz compatibilidade com o que já aprendemos!
#2. É compatível com as bibliotecas mais usadas para visualização
#de dados, como a matplotlib e a seaborn.

#Matplotlib é uma biblioteca de visualização que permite a
#geração de gráficos e visualização dos dados.
#Seaborn é uma alternativa que usa a matplotlib como base,
#permitindo menos controle sobre o resultado final mas
#oferecendo maior estética e facilidade de uso.

#no vscode: pip install pandas
#no anaconda: conda install pandas

In [ ]:
#Series e Dataframes
#1. Series
#São arrays 1D que possuem um nome (label). Semelhante a uma coluna.
#2. Dataframes
#São estruturas de dados 2D. Semelhante a uma tabela

In [7]:
import pandas as pd
import random

In [ ]:
#criando um dataframe
dados = {
    'nome': ['joão', 'carlos', 'sabrina', 'camila', 'mara'],
    'idade': [22, 35, 21, 34, 47],
    'salario': [1000.0, 2000.0, 3000.0, 4000.0, 5000.0]
}
df = pd.DataFrame(dados)
df

      nome  idade  salario
0     joão     22   1000.0
1   carlos     35   2000.0
2  sabrina     21   3000.0
3   camila     34   4000.0
4     mara     47   5000.0

In [ ]:
#acessando uma coluna do dataframe
dados = {
    'nome': ['joão', 'carlos', 'sabrina', 'camila', 'mara'],
    'idade': [22, 35, 21, 34, 47],
    'salario': [1000.0, 2000.0, 3000.0, 4000.0, 5000.0]
}
df = pd.DataFrame(dados)
df['nome']

0       joão
1     carlos
2    sabrina
3     camila
4       mara
Name: nome, dtype: object

In [ ]:
#percorrendo uma coluna com loop
dados = {
    'nome': ['joão', 'carlos', 'sabrina', 'camila', 'mara'],
    'idade': [22, 35, 21, 34, 47],
    'salario': [1000.0, 2000.0, 3000.0, 4000.0, 5000.0]
}
df = pd.DataFrame(dados)
for p in df['nome'].items():
  print(p)

(0, 'joão')
(1, 'carlos')
(2, 'sabrina')
(3, 'camila')
(4, 'mara')

In [ ]:
#Exercício I
#1. Crie uma lista contendo 10 nomes de pessoas
#2. Crie uma lista contendo 10 salários aleatórios, variando entre 0 e
#10.000. Use random para gerar os números
#3. Crie um dicionário juntando as duas informações acima.
#4. Use o dicionário para criar um dataframe
import random

nomes = ['caio', 'sara', 'helo', 'gabi', 'lari', 'danny', 'arthur', 'ana', 'olga', 'richard']
salarios = []
for i in range(10):
  salarios.append(random.random() * 10000)

dados = {
    'nomes': nomes,
    'salarios': salarios
}

df = pd.DataFrame(dados)
df

     nomes     salarios
0     caio   138.672619
1     sara  3674.914838
2     helo  6188.887885
3     gabi  4595.415863
4     lari  4226.832994
5    danny  7796.608759
6   arthur  2708.512633
7      ana  6572.973393
8     olga  3114.448077
9  richard  6246.279116

In [ ]:
#Exercício 2
#Imprima todos os salários, acessando a coluna correta no dataframe e
#iterando sobre o resultado de .items()
for p in df['salarios'].items():
  print(p)

(0, 138.6726192737342)
(1, 3674.914838075316)
(2, 6188.887885441577)
(3, 4595.415863041816)
(4, 4226.832994056793)
(5, 7796.608758750752)
(6, 2708.5126327978614)
(7, 6572.973392648291)
(8, 3114.448076807849)
(9, 6246.279116038875)

In [ ]:
#Exercício 3
#Encontre o maior salário. Use o looping for para verificar qual é o
#maior salário e imprima seu valor e qual é a posição dele na coluna.
maior = 0
idx_maior = -1
for i, valor in df['salarios'].items():
  if maior < valor:
    maior = valor
    idx_maior = i

print(f'O maior salário é {maior} e está na posição {idx_maior}')

O maior salário é 7796.608758750752 e está na posição 5

In [ ]:
#acessando um elemento da coluna por índice
col = df['salarios']
print(col[0])

138.6726192737342

In [ ]:
#Exercício 4
#A partir do que encontramos no exercício 3…
#Imprima o nome da pessoa com o maior salário. Use a posição
#encontrada no exercício 3 para achar o nome da pessoa.
maior = 0
idx_maior = -1
for i, valor in df['salarios'].items():
  if maior < valor:
    maior = valor
    idx_maior = i

nome = df['nomes'][idx_maior]
print(f'{nome} possui o maior salário: {maior}')

danny possui o maior salário: 7796.608758750752

In [ ]:
#funções úteis presentes na coluna
col = df['salarios']
print(col.max()) #valor máximo
print(col.min()) #valor mínimo
print(col.mean()) #valor médio
print(col.argmax()) #posição do valor máximo
print(col.argmin()) #posição do valor mínimo
print(col.count()) #número de itens

7796.608758750752
138.6726192737342
4526.354617693286
5
0
10

In [ ]:
#Exercício 5
#Imprima o nome da pessoa com o maior salário. Use os métodos de
#coluna para achar a posição com o maior salário.
indice = col.argmax()
nome = df['nomes'][indice]
print(nome)

danny

In [ ]:
#Exercício 6
#Imprima os nomes das pessoas cujo salário é abaixo da média.
media = col.mean()
for i in df['salarios']:
  if i < media:
    print(i)

138.6726192737342
3674.914838075316
4226.832994056793
2708.5126327978614
3114.448076807849

In [ ]:
#versão com filtro
media = df['salarios'].mean()
filtro = df[df['salarios'] < media]
print(filtro)

    nomes     salarios
0    caio   138.672619
1    sara  3674.914838
4    lari  4226.832994
6  arthur  2708.512633
8    olga  3114.448077

In [5]:
#criando dataframes a partir de um CSV
df = pd.read_csv('dados.csv')

In [8]:
#Exercício 7
#Vamos criar um arquivo CSV e lê-lo usando pandas.
#1. Crie uma lista de nomes. Ex: nomes = [ “Julia”, “Pedro”, “João”…]
#2. Crie uma lista de nomes de disciplinas. Ex: disciplinas =
#[“matemática”, “física”, “português” …]
#3. Abra um arquivo dados.csv para escrita (w)
#4. Escreva o cabeçalho: nome,disciplina,nota
#5. Gere 1 linha para cada nome x disciplina, criando uma nota
#aleatória com random, de 0 a 10.
nomes = ['sara', 'caio', 'helo']
disciplinas = ['algoritmos', 'banco de dados', 'pre-calculo']

with open('dados.csv', 'w') as arquivo:
  arquivo.write('nome,disciplina,nota\n')
  for nome in nomes:
    for disc in disciplinas:
      nota = random.random() * 10
      print(f'{nome}, {disc}, {nota:.2f}')
      arquivo.write(f'{nome}, {disc}, {nota:.2f}\n')

sara, algoritmos, 4.15
sara, banco de dados, 9.27
sara, pre-calculo, 3.34
caio, algoritmos, 7.61
caio, banco de dados, 3.24
caio, pre-calculo, 9.35
helo, algoritmos, 7.56
helo, banco de dados, 5.63
helo, pre-calculo, 5.52

In [9]:
#Exercício 08
##Carregue o arquivo dados.csv em um dataframe e exiba:
#1. O aluno com a maior nota
#2. O aluno com a menor nota
#3. A quantidade de alunos acima da media
#4. A quantidade de alunos abaixo da media
#Obs: use os métodos de coluna para calcular as estatísticas requisitas
#acima.
df = pd.read_csv('dados.csv')

maior_nota = df['nota'].max()
maior_nota_idx = df['nota'].argmax()

menor_nota = df['nota'].min()
menor_nota_idx = df['nota'].argmin()

aluno_maior = df['nome'][maior_nota_idx]
print(f'O aluno {nome} possui a maior nota: {maior_nota}')

aluno_menor = df['nome'][menor_nota_idx]
print(f'O aluno {nome} possui a menor nota: {menor_nota}')

media = df['nota'].mean()
print(df[df['nota'] > media])
print(df[df['nota'] < media])

lista_maior = []
for i in df['nota']:
  if i > media:
    lista_maior.append(i)
print(f'O número de notas acima da média é {len(lista_maior)}')

lista_menor = []
for i in df['nota']:
  if i < media:
    lista_menor.append(i)
print(f'O número de notas abaixo da média é {len(lista_menor)}')

O aluno helo possui a maior nota: 9.35
O aluno helo possui a menor nota: 3.24
   nome       disciplina  nota
1  sara   banco de dados  9.27
3  caio       algoritmos  7.61
5  caio      pre-calculo  9.35
6  helo       algoritmos  7.56
   nome       disciplina  nota
0  sara       algoritmos  4.15
2  sara      pre-calculo  3.34
4  caio   banco de dados  3.24
7  helo   banco de dados  5.63
8  helo      pre-calculo  5.52
O número de alunos acima da média é 4
O número de alunos abaixo da média é 5

In [11]:
#Exercício 09
#Vamos “separar” nossos dados em tabelas, cada uma em um arquivo
#CSV separado e ler tudo usando pandas.
#1. Crie um dicionário de ID e nome de disciplinas. Ex: disciplinas = {1:
#“matemática”, 2: “física”, 3: “português” …}
#2. Crie uma lista de nomes. Ex: nomes = [ “Julia”, “Pedro”, “João”…]
#3. Abra um arquivo chamado materias.csv para escrita e inclua o
#abeçalho codigo_disciplina, nome_disciplina
#4. Para cada item no dicionário do passo 1, inclua uma linha no
#arquivo com “chave,valor” do dicionário (que é o código e o nome
#da disciplina)
disciplinas = {
    1: 'MLOps',
    2: 'business intelligence',
    3: 'banco de dados',
    4: 'big data',
    5: 'computação em nuvem',
    6: 'machine learning'
    }
nomes = ['sara', 'caio', 'helo']

with open('materias.csv', 'w') as arquivo:
  arquivo.write('codigo_disciplina,nome_disciplina\n')
  for chave, valor in disciplinas.items():
    arquivo.write(f'{chave},{valor}\n')

In [12]:
#Exercício 10
#Vamos “separar” nossos dados de notas:
#1. Abra um arquivo chamado notas.csv para escrita e inclua o
#cabeçalho aluno,codigo_disciplina,nota.
#2. Para cada nome da lista de nomes e para cada chave do dicionário
#de disciplinas, inclua uma linha no arquivo com o valor
#“nome,chave do dicionário,nota”. Gere a nota usando random de
#0 a 10.
with open('notas.csv', 'w') as arq:
  arq.write('aluno,codigo_disciplina,nota\n')
  for aluno in nomes:
    for codigo_disciplina in disciplinas.keys():
      nota = random.random() * 10
      arq.write(f'{aluno},{codigo_disciplina},{nota:.2f}\n')

In [19]:
#Iterando sobre cada linha de um Dataframe
df = pd.read_csv('notas.csv')
for indice, linha in df.iterrows():
  print(linha)

aluno                sara
codigo_disciplina       1
nota                 6.65
Name: 0, dtype: object
aluno                sara
codigo_disciplina       2
nota                 0.56
Name: 1, dtype: object
aluno                sara
codigo_disciplina       3
nota                 6.01
Name: 2, dtype: object
aluno                sara
codigo_disciplina       4
nota                 2.13
Name: 3, dtype: object
aluno                sara
codigo_disciplina       5
nota                 2.37
Name: 4, dtype: object
aluno                sara
codigo_disciplina       6
nota                 8.12
Name: 5, dtype: object
aluno                caio
codigo_disciplina       1
nota                 4.89
Name: 6, dtype: object
aluno                caio
codigo_disciplina       2
nota                 1.01
Name: 7, dtype: object
aluno                caio
codigo_disciplina       3
nota                  0.1
Name: 8, dtype: object
aluno                caio
codigo_disciplina       4
nota                 2.86
Name: 9, dtype: object
aluno                caio
codigo_disciplina       5
nota                 3.56
Name: 10, dtype: object
aluno                caio
codigo_disciplina       6
nota                 0.54
Name: 11, dtype: object
aluno                helo
codigo_disciplina       1
nota                 0.47
Name: 12, dtype: object
aluno                helo
codigo_disciplina       2
nota                 8.49
Name: 13, dtype: object
aluno                helo
codigo_disciplina       3
nota                 3.12
Name: 14, dtype: object
aluno                helo
codigo_disciplina       4
nota                 6.47
Name: 15, dtype: object
aluno                helo
codigo_disciplina       5
nota                 6.84
Name: 16, dtype: object
aluno                helo
codigo_disciplina       6
nota                 6.04
Name: 17, dtype: object

In [23]:
#Exercício 11
#Crie um dicionário a partir do dataframe das matérias. A chave do
#dicionário deverá ser o código da matéria e o valor deverá ser o nome
#da matéria
df = pd.read_csv('materias.csv')
dic = {}
for indice, linha in df.iterrows():
  codigo = linha['codigo_disciplina']
  nome = linha['nome_disciplina']
  dic[codigo] = nome
print(dic)

{1: 'MLOps', 2: 'business intelligence', 3: 'banco de dados', 4: 'big data', 5: 'computação em nuvem', 6: 'machine learning'}

In [27]:
#modificando o index do dataframe
df = pd.read_csv('materias.csv')
df2 = df.set_index('codigo_disciplina')
print(df2)

                         nome_disciplina
codigo_disciplina
1                                  MLOps
2                  business intelligence
3                         banco de dados
4                               big data
5                    computação em nuvem
6                       machine learning

In [28]:
#acessando um registro por índice
df = pd.read_csv('materias.csv')
df2 = df.set_index('codigo_disciplina')
#df2.drop(columns='nome_disciplina', inplace=True) <- exclui a coluna
nome = df2.at[1, 'nome_disciplina'] #1 = índice, '' = coluna
print(nome)

MLOps

In [32]:
#acessando a linha toda
df = pd.read_csv('notas.csv')
df.loc[3]

aluno                sara
codigo_disciplina       4
nota                 2.13
Name: 3, dtype: object

In [33]:
#acessando duas linhas
df = pd.read_csv('notas.csv')
df.loc[3:4]

  aluno  codigo_disciplina  nota
3  sara                  4  2.13
4  sara                  5  2.37

In [41]:
#acessando uma coluna específica da linha (ou mais)
df = pd.read_csv('notas.csv')
df.loc[3, ['aluno', 'nota']]

aluno    sara
nota     2.13
Name: 3, dtype: object

In [65]:
#Exercício 12
#Vamos “juntar” nossos dados manualmente:
#1. Abra o arquivo chamado materias.csv como um dataframe
#2. Abra o arquivo chamado notas.csv como um dataframe
#3. Imprima a lista de alunos e suas notas com o formato:
#Aluno, nome da matéria, nota
df_materias = pd.read_csv('materias.csv')
df_materias = df_materias.set_index('codigo_disciplina')
df_notas = pd.read_csv('notas.csv')

for indice, linha in df_notas.iterrows():
  nome_aluno = linha['aluno']
  codigo = linha['codigo_disciplina']
  nota = linha['nota']
  nome_materia = df_materias.loc[codigo, 'nome_disciplina']
  print(f'{nome_aluno}, {nome_materia}, {nota}')

sara, MLOps, 6.65
sara, business intelligence, 0.56
sara, banco de dados, 6.01
sara, big data, 2.13
sara, computação em nuvem, 2.37
sara, machine learning, 8.12
caio, MLOps, 4.89
caio, business intelligence, 1.01
caio, banco de dados, 0.1
caio, big data, 2.86
caio, computação em nuvem, 3.56
caio, machine learning, 0.54
helo, MLOps, 0.47
helo, business intelligence, 8.49
helo, banco de dados, 3.12
helo, big data, 6.47
helo, computação em nuvem, 6.84
helo, machine learning, 6.04

In [70]:
#Exercício 13
#Refaça o exercício 12, mas agora imprima a lista de alunos e suas
#notas com o formato:
#Aluno:
#- matemática: 5.6
#- portugues: 7.2
#Obs: para juntarmos as notas do aluno, precisamos usar um
#dicionário!
dic = {
    'aluno': [],
    'disciplina': [],
    'nota': []
    }

for indice, linha in df_notas.iterrows():
  nome = linha['aluno']
  codigo = linha['codigo_disciplina']
  nome_materia = df_materias.loc[codigo, 'nome_disciplina']
  nota = linha['nota']
  dic['aluno'].append(nome)
  dic['disciplina'].append(nome_materia)
  dic['nota'].append(nota)
df = pd.DataFrame(dic)
print(df)

   aluno             disciplina  nota
0   sara                  MLOps  6.65
1   sara  business intelligence  0.56
2   sara         banco de dados  6.01
3   sara               big data  2.13
4   sara    computação em nuvem  2.37
5   sara       machine learning  8.12
6   caio                  MLOps  4.89
7   caio  business intelligence  1.01
8   caio         banco de dados  0.10
9   caio               big data  2.86
10  caio    computação em nuvem  3.56
11  caio       machine learning  0.54
12  helo                  MLOps  0.47
13  helo  business intelligence  8.49
14  helo         banco de dados  3.12
15  helo               big data  6.47
16  helo    computação em nuvem  6.84
17  helo       machine learning  6.04