<a href="https://colab.research.google.com/github/sararotenski/AlgoritmosEProgramacao/blob/main/aula_2005.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Pandas
#Ele facilita a manipulação e a análise de dados tabulares
#Pandas utiliza numpy arrays como estrutura de dados base, o
#que traz compatibilidade com o que já aprendemos!
#2. É compatível com as bibliotecas mais usadas para visualização
#de dados, como a matplotlib e a seaborn.

#Matplotlib é uma biblioteca de visualização que permite a
#geração de gráficos e visualização dos dados.
#Seaborn é uma alternativa que usa a matplotlib como base,
#permitindo menos controle sobre o resultado final mas
#oferecendo maior estética e facilidade de uso.

#no vscode: pip install pandas
#no anaconda: conda install pandas

In [ ]:
#Series e Dataframes
#1. Series
#São arrays 1D que possuem um nome (label). Semelhante a uma coluna.
#2. Dataframes
#São estruturas de dados 2D. Semelhante a uma tabela

In [3]:
import pandas as pd

In [14]:
#criando um dataframe
dados = {
    'nome': ['joão', 'carlos', 'sabrina', 'camila', 'mara'],
    'idade': [22, 35, 21, 34, 47],
    'salario': [1000.0, 2000.0, 3000.0, 4000.0, 5000.0]
}
df = pd.DataFrame(dados)
df

      nome  idade  salario
0     joão     22   1000.0
1   carlos     35   2000.0
2  sabrina     21   3000.0
3   camila     34   4000.0
4     mara     47   5000.0

In [17]:
#acessando uma coluna do dataframe
dados = {
    'nome': ['joão', 'carlos', 'sabrina', 'camila', 'mara'],
    'idade': [22, 35, 21, 34, 47],
    'salario': [1000.0, 2000.0, 3000.0, 4000.0, 5000.0]
}
df = pd.DataFrame(dados)
df['nome']

0       joão
1     carlos
2    sabrina
3     camila
4       mara
Name: nome, dtype: object

In [22]:
#percorrendo uma coluna com loop
dados = {
    'nome': ['joão', 'carlos', 'sabrina', 'camila', 'mara'],
    'idade': [22, 35, 21, 34, 47],
    'salario': [1000.0, 2000.0, 3000.0, 4000.0, 5000.0]
}
df = pd.DataFrame(dados)
for p in df['nome'].items():
  print(p)

(0, 'joão')
(1, 'carlos')
(2, 'sabrina')
(3, 'camila')
(4, 'mara')

In [23]:
#Exercício I
#1. Crie uma lista contendo 10 nomes de pessoas
#2. Crie uma lista contendo 10 salários aleatórios, variando entre 0 e
#10.000. Use random para gerar os números
#3. Crie um dicionário juntando as duas informações acima.
#4. Use o dicionário para criar um dataframe
import random

nomes = ['caio', 'sara', 'helo', 'gabi', 'lari', 'danny', 'arthur', 'ana', 'olga', 'richard']
salarios = []
for i in range(10):
  salarios.append(random.random() * 10000)

dados = {
    'nomes': nomes,
    'salarios': salarios
}

df = pd.DataFrame(dados)
df

     nomes     salarios
0     caio   138.672619
1     sara  3674.914838
2     helo  6188.887885
3     gabi  4595.415863
4     lari  4226.832994
5    danny  7796.608759
6   arthur  2708.512633
7      ana  6572.973393
8     olga  3114.448077
9  richard  6246.279116

In [24]:
#Exercício 2
#Imprima todos os salários, acessando a coluna correta no dataframe e
#iterando sobre o resultado de .items()
for p in df['salarios'].items():
  print(p)

(0, 138.6726192737342)
(1, 3674.914838075316)
(2, 6188.887885441577)
(3, 4595.415863041816)
(4, 4226.832994056793)
(5, 7796.608758750752)
(6, 2708.5126327978614)
(7, 6572.973392648291)
(8, 3114.448076807849)
(9, 6246.279116038875)

In [25]:
#Exercício 3
#Encontre o maior salário. Use o looping for para verificar qual é o
#maior salário e imprima seu valor e qual é a posição dele na coluna.
maior = 0
idx_maior = -1
for i, valor in df['salarios'].items():
  if maior < valor:
    maior = valor
    idx_maior = i

print(f'O maior salário é {maior} e está na posição {idx_maior}')

O maior salário é 7796.608758750752 e está na posição 5

In [27]:
#acessando um elemento da coluna por índice
col = df['salarios']
print(col[0])

138.6726192737342

In [31]:
#Exercício 4
#A partir do que encontramos no exercício 3…
#Imprima o nome da pessoa com o maior salário. Use a posição
#encontrada no exercício 3 para achar o nome da pessoa.
maior = 0
idx_maior = -1
for i, valor in df['salarios'].items():
  if maior < valor:
    maior = valor
    idx_maior = i

nome = df['nomes'][idx_maior]
print(f'{nome} possui o maior salário: {maior}')

danny possui o maior salário: 7796.608758750752

In [33]:
#funções úteis presentes na coluna
col = df['salarios']
print(col.max()) #valor máximo
print(col.min()) #valor mínimo
print(col.mean()) #valor médio
print(col.argmax()) #posição do valor máximo
print(col.argmin()) #posição do valor mínimo
print(col.count()) #número de itens

7796.608758750752
138.6726192737342
4526.354617693286
5
0
10

In [34]:
#Exercício 5
#Imprima o nome da pessoa com o maior salário. Use os métodos de
#coluna para achar a posição com o maior salário.
indice = col.argmax()
nome = df['nomes'][indice]
print(nome)

danny

In [47]:
#Exercício 6
#Imprima os nomes das pessoas cujo salário é abaixo da média.
media = col.mean()
for i in df['salarios']:
  if i < media:
    print(i)

138.6726192737342
3674.914838075316
4226.832994056793
2708.5126327978614
3114.448076807849

In [52]:
#versão com filtro
media = df['salarios'].mean()
filtro = df[df['salarios'] < media]
print(filtro)

    nomes     salarios
0    caio   138.672619
1    sara  3674.914838
4    lari  4226.832994
6  arthur  2708.512633
8    olga  3114.448077

In [76]:
#criando dataframes a partir de um CSV
df = pd.read_csv('dados.csv')

In [74]:
#Exercício 7
#Vamos criar um arquivo CSV e lê-lo usando pandas.
#1. Crie uma lista de nomes. Ex: nomes = [ “Julia”, “Pedro”, “João”…]
#2. Crie uma lista de nomes de disciplinas. Ex: disciplinas =
#[“matemática”, “física”, “português” …]
#3. Abra um arquivo dados.csv para escrita (w)
#4. Escreva o cabeçalho: nome,disciplina,nota
#5. Gere 1 linha para cada nome x disciplina, criando uma nota
#aleatória com random, de 0 a 10.
nomes = ['sara', 'caio', 'helo']
disciplinas = ['algoritmos', 'banco de dados', 'pre-calculo']

with open('dados.csv', 'w') as arquivo:
  arquivo.write('nome,disciplina,nota\n')
  for nome in nomes:
    for disc in disciplinas:
      nota = random.random() * 10
      print(f'{nome}, {disc}, {nota:.2f}')
      arquivo.write(f'{nome}, {disc}, {nota:.2f}\n')

sara, algoritmos, 2.33
sara, banco de dados, 9.66
sara, pre-calculo, 5.79
caio, algoritmos, 2.95
caio, banco de dados, 2.84
caio, pre-calculo, 4.60
helo, algoritmos, 8.19
helo, banco de dados, 2.73
helo, pre-calculo, 1.02

In [83]:
#Exercício 08
##Carregue o arquivo dados.csv em um dataframe e exiba:
#1. O aluno com a maior nota
#2. O aluno com a menor nota
#3. A quantidade de alunos acima da media
#4. A quantidade de alunos abaixo da media
#Obs: use os métodos de coluna para calcular as estatísticas requisitas
#acima.
df = pd.read_csv('dados.csv')

maior_nota = df['nota'].max()
maior_nota_idx = df['nota'].argmax()

menor_nota = df['nota'].min()
menor_nota_idx = df['nota'].argmin()

aluno_maior = df['nome'][maior_nota_idx]
print(f'O aluno {nome} possui a maior nota: {maior_nota}')

aluno_menor = df['nome'][menor_nota_idx]
print(f'O aluno {nome} possui a menor nota: {menor_nota}')

media = df['nota'].mean()
print(df[df['nota'] > media])
print(df[df['nota'] < media])

O aluno helo possui a maior nota: 9.66
O aluno helo possui a menor nota: 1.02
   nome       disciplina  nota
1  sara   banco de dados  9.66
2  sara      pre-calculo  5.79
5  caio      pre-calculo  4.60
6  helo       algoritmos  8.19
   nome       disciplina  nota
0  sara       algoritmos  2.33
3  caio       algoritmos  2.95
4  caio   banco de dados  2.84
7  helo   banco de dados  2.73
8  helo      pre-calculo  1.02